-- =====================================================================
--  TỆP NÀY ĐÃ TẮT — CHẠY NÓ KHÔNG TẠO RA GÌ CẢ
--
--  Mọi câu lệnh bên dưới đều nằm trong comment. Giữ tệp lại để đối chiếu,
--  nhưng ĐỪNG nạp nó rồi ngồi chờ có tài khoản đăng nhập.
--
--  Tạo vai trò + cửa hàng + tài khoản quản trị đầu tiên bằng:
--      cd api && go run ./cmd/tao-admin        (máy cá nhân)
--      sudo selliotech-tao-admin               (máy chủ thật)
--
--  Lý do thay: từ khi đăng nhập bằng 3 ô (mã cửa hàng · tên đăng nhập ·
--  mật khẩu), một tài khoản dùng được phải gắn với một dòng trong bảng
--  tenants; mà mật khẩu băm sẵn nằm công khai trong repo thì bản cài nào
--  cũng dùng chung đúng một mật khẩu ai cũng đọc được.
-- =====================================================================

-- -- =====================================================================
-- --  SELLIOTECH — SEED TỐI THIỂU (bản cũ, giữ để đối chiếu)
-- --  Chạy sau khi lược đồ đã có:
-- --      cd api && go run ./cmd/migrate chay
-- --      mysql -u root selliotech < ../database/seed.sql
-- --
-- --  Chỉ có thứ BẮT BUỘC để đăng nhập được khu quản trị: bảng vai trò và một
-- --  tài khoản super admin. Không kèm dữ liệu mẫu (sản phẩm, đơn hàng...) —
-- --  đây là bản cài trắng, hàng hoá do người dùng tự nhập.
-- --
-- --  Các khoá `settings` KHÔNG cần seed: registry trong
-- --  api/internal/service/setting_service.go đã mang sẵn giá trị mặc định,
-- --  khoá chưa có dòng trong database vẫn cho ra đúng hành vi mặc định.
-- --
-- --  Tài khoản mặc định:
-- --    email:    admin@selliotech.local
-- --    password: Admin@123
-- --  => ĐỔI MẬT KHẨU NGAY sau khi triển khai thật.
-- --
-- --  KHÔNG viết USE ở đây: tên database khác nhau ở từng môi trường, cứ nạp
-- --  vào đúng database đã chọn ở dòng lệnh / .env.
-- -- =====================================================================

-- SET NAMES utf8mb4;

-- -- ---------- Vai trò (RBAC) ----------
-- -- Bốn mã này được middleware/RBAC tham chiếu thẳng, thiếu là chặn nhầm quyền.
-- INSERT IGNORE INTO roles (id, name, display_name, description, created_at, updated_at) VALUES
--   (1, 'super_admin', 'Super Admin',   'Toàn quyền hệ thống',        NOW(3), NOW(3)),
--   (2, 'admin',       'Quản trị viên', 'Quản lý sản phẩm, đơn hàng', NOW(3), NOW(3)),
--   (3, 'staff',       'Nhân viên',     'Xử lý đơn hàng, kho',        NOW(3), NOW(3)),
--   (4, 'customer',    'Khách hàng',    'Người dùng cuối',            NOW(3), NOW(3));

-- -- ---------- Tài khoản quản trị đầu tiên ----------
-- -- password_hash là bcrypt của "Admin@123".
-- -- deleted_at=NULL: chạy lại seed sẽ khôi phục tài khoản nếu lỡ xoá mềm lúc thử.
-- INSERT INTO users (id, role_id, full_name, email, phone, password_hash, status, email_verified_at, created_at, updated_at) VALUES
--   (1, 1, 'Super Admin', 'admin@selliotech.local', '0900000001',
--    '$2y$10$/ltwtBCwQxRWgAwbf9nzyOxnMtx7F5QuyvZEugkB0SPFzcwlL21.u',
--    'active', NOW(3), NOW(3), NOW(3))
-- ON DUPLICATE KEY UPDATE
--   role_id = VALUES(role_id), full_name = VALUES(full_name),
--   status = VALUES(status), deleted_at = NULL;

-- -- ---------- Cấu hình ----------
-- -- Chỉ đè đúng khoá mà mặc định trong registry còn mang tên dự án gốc; những
-- -- khoá khác để trống cho registry tự lo (xem đầu tệp).
-- INSERT IGNORE INTO settings (`key`, `value`, `group`, created_at, updated_at) VALUES
--   ('site_name', 'Selliotech', 'general', NOW(3), NOW(3));

-- -- =====================================================================
-- --  KẾT THÚC SEED
-- -- =====================================================================
